name: naja
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.10
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  place_picker_google: ^0.0.14

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true

 
  assets:
    - assets/


 
